### DATA PRE-PROCESSING
- Data Type Correction 
- Duplicate data handling
- Dropping Irrelevant Columns
- ***Objective*** : The goal of this step is to clean and prepare the raw Insurance_Customer_Response_Prediction dataset so it can be used effectively for **EDA** & **Model Training**.
  
- ****Output**** : A **Cleaned_dataset** ready for:EDA,Feature Engineering,ML Model Training.

In [1]:
#Imports
import numpy as np
import pandas as pd

In [2]:
#Load Data
DATA_PATH=r"C:\Users\dshar\OneDrive\Pictures\Desktop\Insurance_Customer_Response_Pred\DATA\data.csv"
RAW_DATA=pd.read_csv(DATA_PATH)
RAW_DATA.head()

,id,Gender,Age,Driving_License,Region_Code,Previously_Insured,Vehicle_Age,Vehicle_Damage,Annual_Premium,Policy_Sales_Channel,Vintage,Response
0,1,Male,44,1,28.0,0,> 2 Years,Yes,40454.0,26.0,217,1
1,2,Male,76,1,3.0,0,1-2 Year,No,33536.0,26.0,183,0
2,3,Male,47,1,28.0,0,> 2 Years,Yes,38294.0,26.0,27,1
3,4,Male,21,1,11.0,1,< 1 Year,No,28619.0,152.0,203,0
4,5,Female,29,1,41.0,1,< 1 Year,No,27496.0,152.0,39,0

In [3]:
#Copy the data
df=RAW_DATA.copy()
df.head()

,id,Gender,Age,Driving_License,Region_Code,Previously_Insured,Vehicle_Age,Vehicle_Damage,Annual_Premium,Policy_Sales_Channel,Vintage,Response
0,1,Male,44,1,28.0,0,> 2 Years,Yes,40454.0,26.0,217,1
1,2,Male,76,1,3.0,0,1-2 Year,No,33536.0,26.0,183,0
2,3,Male,47,1,28.0,0,> 2 Years,Yes,38294.0,26.0,27,1
3,4,Male,21,1,11.0,1,< 1 Year,No,28619.0,152.0,203,0
4,5,Female,29,1,41.0,1,< 1 Year,No,27496.0,152.0,39,0

In [4]:
# Info of Raw_data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 381109 entries, 0 to 381108
Data columns (total 12 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   id                    381109 non-null  int64
 1   Gender                381109 non-null  object
 2   Age                   381109 non-null  int64
 3   Driving_License       381109 non-null  int64
 4   Region_Code           381109 non-null  float64
 5   Previously_Insured    381109 non-null  int64
 6   Vehicle_Age           381109 non-null  object
 7   Vehicle_Damage        381109 non-null  object
 8   Annual_Premium        381109 non-null  float64
 9   Policy_Sales_Channel  381109 non-null  float64
 10  Vintage               381109 non-null  int64
 11  Response              381109 non-null  int64
dtypes: float64(3), int64(6), object(3)
memory usage: 34.9+ MB

In [5]:
#Meta Data
print("No of Rows:",df.shape[0])
print("No of Columns:",df.shape[1])

No of Rows: 381109
No of Columns: 12

In [7]:
# Column Categorization
all_columns=df.columns.to_list()
num_columns=df.select_dtypes(include="number").columns.to_list()
cat_columns=df.select_dtypes(include="object").columns.to_list()

#PRINTING
print("All Columns:\n",all_columns)
print("\nNumerical Columns:\n",num_columns)
print("\nCategorical Columns:\n",cat_columns)

All Columns:
 ['id', 'Gender', 'Age', 'Driving_License', 'Region_Code', 'Previously_Insured', 'Vehicle_Age', 'Vehicle_Damage', 'Annual_Premium', 'Policy_Sales_Channel', 'Vintage', 'Response']

Numerical Columns:
 ['id', 'Age', 'Driving_License', 'Region_Code', 'Previously_Insured', 'Annual_Premium', 'Policy_Sales_Channel', 'Vintage', 'Response']

Categorical Columns:
 ['Gender', 'Vehicle_Age', 'Vehicle_Damage']

In [8]:
#Datatype of Columns
print("\nDtypes:\n",df.dtypes)

Dtypes:
 id                        int64
Gender                   object
Age                       int64
Driving_License           int64
Region_Code             float64
Previously_Insured        int64
Vehicle_Age              object
Vehicle_Damage           object
Annual_Premium          float64
Policy_Sales_Channel    float64
Vintage                   int64
Response                  int64
dtype: object

In [11]:
#Checking Missing Values 
missing_values = df.isnull().sum()
print("\nMissing values:\n", missing_values)

Missing values:
 id                      0
Gender                  0
Age                     0
Driving_License         0
Region_Code             0
Previously_Insured      0
Vehicle_Age             0
Vehicle_Damage          0
Annual_Premium          0
Policy_Sales_Channel    0
Vintage                 0
Response                0
dtype: int64

In [12]:
#Duplicate
duplicated_Val = df.duplicated().sum()
if duplicated_Val == 0:
    print("There are no duplicate values in the dataset.")
else:
    print(f"There are {duplicated_Val} duplicate values in the dataset.")

There are no duplicate values in the dataset.

In [13]:
#Dropping irrelevant Column(id)
df.drop(columns=["id"],axis=1,inplace=True)

In [14]:
#Encoding the Column "Vehicle_Age"
df["Vehicle_Age"].unique()
print("Unique values in Vehicle_Age:", df["Vehicle_Age"].unique())

#Mapping dictionary for encoding
vehicle_age_map = {
    "< 1 Year": 0,
    "1-2 Year": 1,
    "> 2 Years": 2}
# Apply encoding
df["Vehicle_Age"] = df["Vehicle_Age"].map(vehicle_age_map).astype(int)

Unique values in Vehicle_Age: ['> 2 Years' '1-2 Year' '< 1 Year']

In [15]:
#Checking Unique values 
print(df["Region_Code"].nunique())
print(df["Policy_Sales_Channel"].nunique())

53
155

In [16]:
#Converting to Categorical Columns
df["Region_Code"] = df["Region_Code"].astype("object")
df["Policy_Sales_Channel"] = df["Policy_Sales_Channel"].astype("object")

In [17]:
#Info after Cleaning 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 381109 entries, 0 to 381108
Data columns (total 11 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Gender                381109 non-null  object
 1   Age                   381109 non-null  int64
 2   Driving_License       381109 non-null  int64
 3   Region_Code           381109 non-null  object
 4   Previously_Insured    381109 non-null  int64
 5   Vehicle_Age           381109 non-null  int64
 6   Vehicle_Damage        381109 non-null  object
 7   Annual_Premium        381109 non-null  float64
 8   Policy_Sales_Channel  381109 non-null  object
 9   Vintage               381109 non-null  int64
 10  Response              381109 non-null  int64
dtypes: float64(1), int64(6), object(4)
memory usage: 32.0+ MB

In [18]:
#Saving Cleaned DAta 
CLEAN_DATA_PATH = r"C:\Users\dshar\OneDrive\Pictures\Desktop\Insurance_Customer_Response_Pred\DATA\Cleaned_data.csv"
df.to_csv(CLEAN_DATA_PATH, index=False)
print("Clean_data saved successfully.")

Clean_data saved successfully.

In [19]:
print("No of Rows in Cleaned_data:", df.shape[0])

print("No of Columns in Cleaned_data:", df.shape[1])

No of Rows in Cleaned_data: 381109
No of Columns in Cleaned_data: 11